services:
  postgres:
    image: postgres
    container_name: schedly-postgres
    env_file:
      - .env.docker
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  postgres_data:
