services:
  postgres:
    image: postgres
    container_name: schedly-postgres
    env_file:
      - docker.env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  maildev:
    image: soulteary/maildev
    container_name: schedly-maildev
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  postgres_data:
